<?php
use PhpOffice\PhpWord\Element\Section;
use PhpOffice\PhpWord\Shared\Converter;


$vendorDirPath = realpath(__DIR__ . '/vendor');
if (file_exists($vendorDirPath . '/autoload.php')) {
    require $vendorDirPath . '/autoload.php';
} else {
    throw new Exception(
        sprintf(
            'Could not find file \'%s\'. It is generated by Composer. Use \'install --prefer-source\' or \'update --prefer-source\' Composer commands to move forward.',
            $vendorDirPath . '/autoload.php'
        )
    );
}
//Array asociativo
$arrayAsociativo = array("titulo" => "CURRICULUM VITAE", "nombre"=>"Diego Garcia Flores",
 "tituloDos"=>"¿Quien Soy?", "presentacion" => "Soy desarrollador de aplicaciones web Tengo de experiencia programando un año y medio aproximado actualmente sigo terminando de sacar el grado superior Tengo el grado medio de sistemas microinformatico y redes",
"tituloTres" => "Mi experiencia", "expPersonal" =>"Soy desarrollador de aplicaciones web Tengo de experiencia programando un año y medio aproximado actualmente sigo terminando de sacar el grado superior He trabajado durante 6 meses en una tienda de informatica arreglando ordenadores Hago trabajos de vez en cuando por mi cuenta",
"tituloCuatro" => "Paginas Web", "paginasExp" =>"En tema de las paginas web tengo hechas en total unas 3 paginas colgadas en wordpress una de ellas tenia incluido una tienda online y era una pagina sobre videojuegos, tambien he hecho paginas web sobre peluquerias y un restaurante"
);

// Creamos el documento Word
$phpWord = new \PhpOffice\PhpWord\PhpWord();

// Hacemos referencia para añadirle la seccion
$section = $phpWord->addSection();


// Añadimos elemtos de texto a nuestro word
    $section->addText(
        $arrayAsociativo["titulo"],
        array('name' => 'Tahoma', 'size' => 18, 'color' => 'AABBFF', 'bold' => true)
    );

    $section->addText(
        $arrayAsociativo["nombre"],
        array('name' => 'Tahoma', 'size' => 14)
    );

    $section->addText(
        $arrayAsociativo['tituloDos'],
        array('name' => 'Ubuntu', 'size' => 16)
    );

    $section->addText(
        $arrayAsociativo['presentacion'],
        array('name' => 'Ubuntu', 'size' => 10)
    );
    
    $section->addText(
        $arrayAsociativo['tituloTres'],
        array('name' => 'Ubuntu', 'size' => 16)
    );

    $section->addText(
        $arrayAsociativo['expPersonal'],
        array('name' => 'Ubuntu', 'size' => 10)
    );

    $section->addText(
        $arrayAsociativo['tituloCuatro'],
        array('name' => 'Ubuntu', 'size' => 16)
    );
    
    $section->addText(
        $arrayAsociativo['paginasExp'],
        array('name' => 'Ubuntu', 'size' => 10)
    );





//AIncluimos una foto arriba a la derecha
$section->addImage(
    'img/profile.jpg',
    array(
        'width'            => \PhpOffice\PhpWord\Shared\Converter::cmToPixel(3),
        'height'           => \PhpOffice\PhpWord\Shared\Converter::cmToPixel(3),
        'positioning'      => \PhpOffice\PhpWord\Style\Image::POSITION_ABSOLUTE,
        'posHorizontal'    => \PhpOffice\PhpWord\Style\Image::POSITION_HORIZONTAL_RIGHT,
        'posHorizontalRel' => \PhpOffice\PhpWord\Style\Image::POSITION_RELATIVE_TO_PAGE,
        'posVerticalRel'   => \PhpOffice\PhpWord\Style\Image::POSITION_RELATIVE_TO_PAGE,
        'marginLeft'       => \PhpOffice\PhpWord\Shared\Converter::cmToPixel(5.5),
        'marginTop'        => \PhpOffice\PhpWord\Shared\Converter::cmToPixel(5.55),
    )
);

$wrappingStyle = 'square';


// Lo guardamos en un documento word 
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('curriculum.docx');

?>